---
default: true
whitespace: false

# MD001 - Heading levels should only increment by one level at a time
heading-increment: true

# MD003 - Heading style
heading-style:
  style: atx

# MD004 - Unordered list style
ul-style:
  style: dash

# MD005 - Inconsistent indentation for list items at the same level
list-indent: true

# MD006 - Consider starting bulleted lists at the beginning of the line
ul-start-left: true

# MD007 - Unordered list indentation
# 2 is clearly the superior choice, but sadly only 4 is GFM compatible ಠ╭╮ಠ
ul-indent:
  indent: 4

# MD009 - Trailing spaces
no-trailing-spaces:
  br_spaces: 2
  list_item_empty_lines: false

# MD010 - Hard tabs
no-hard-tabs: true

# MD011 - Reversed link syntax
no-reversed-links: true

# MD012 - Multiple consecutive blank lines
no-multiple-blanks: false

# MD013 - Line length
line-length: false

# MD014 - Dollar signs used before commands without showing output
commands-show-output: true

# MD018 - No space after hash on atx style heading
no-missing-space-atx: true

# MD019 - Multiple spaces after hash on atx style heading
no-multiple-space-atx: true

# MD020 - No space inside hashes on closed atx style heading
no-missing-space-closed-atx: true

# MD021 - Multiple spaces inside hashes on closed atx style heading
no-multiple-space-closed-atx: true

# MD022 - Headings should be surrounded by blank lines
blanks-around-headings:
  lines_above: 2
  lines_below: 1

# MD023 - Headings must start at the beginning of the line
heading-start-left: true

# MD024 - Multiple headings with the same content
no-duplicate-heading:
  siblings_only: true

# MD025 - Multiple top level headings in the same document
single-h1: true

# MD026 - Trailing punctuation in heading
no-trailing-punctuation: true

# MD027 - Multiple spaces after blockquote symbol
no-multiple-space-blockquote: true

# MD028 - Blank line inside blockquote
no-blanks-blockquote: true

# MD029 - Ordered list item prefix
ol-prefix:
  style: one

# MD030 - Spaces after list markers
list-marker-space:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# MD031 - Fenced code blocks should be surrounded by blank lines
blanks-around-fences: true

# MD032 - Lists should be surrounded by blank lines
blanks-around-lists: true

# MD033 - Inline HTML
no-inline-html: false

# MD034 - Bare URL used
no-bare-urls: false

# MD035 - Horizontal rule style
hr-style:
  style: "* * *"

# MD036 - Emphasis used instead of a heading
no-emphasis-as-heading: false

# MD037 - Spaces inside emphasis markers
no-space-in-emphasis: true

# MD038 - Spaces inside code span elements
no-space-in-code: true

# MD039 - Spaces inside link text
no-space-in-links: true

# MD040 - Fenced code blocks should have a language specified
fenced-code-language: true

# MD041 - First line in file should be a top level heading
first-line-h1: false

# MD042 - No empty links
no-empty-links: true

# MD043 - Required heading structure
required-headings: true

# MD044 - Proper names should have the correct capitalization
proper-names:
  names:
    - JavaScript

# MD045 - Images should have alternate text (alt text)
no-alt-text: true

# MD046 - Code block style
code-block-style:
  style: fenced

# MD047 - Files should end with a single newline character
single-trailing-newline: true

# MD048 - Code fence style
code-fence-style:
  style: backtick

# MD049 - Emphasis style should be consistent
emphasis-style:
  style: asterisk

# MD050 - Strong style should be consistent
strong-style:
  style: asterisk

# MD051 - Link fragments should be valid
link-fragments: true

# MD052 - Reference links and images should use a label that is defined
reference-links-images: true

# MD053 - Link and image reference definitions should be needed
link-image-reference-definitions: true