---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#############################
# Start the job on all push #
#############################
on:
    # branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint the New File
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          # Config Locations          
          # Below is True to Lint
          VALIDATE_CSS: true
          VALIDATE_DART: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_HTML: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JAVASCRIPT_STANDARD: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          # Warning Notices
          YAML_ERROR_ON_WARNING: false
          # More Config
          DEFAULT_BRANCH: Main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
