name: Lint Filenames

on:
  pull_request:

jobs:
  build:
     runs-on: ubuntu-latest
     steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Filenames
        uses: julie-ng/lowercase-linter@v1
        id: lint_filenames
        continue-on-error: true
        with:
          path: '.'
          pr-comment: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
